//
// Created by 12181 on 2017/12/2.
//

#ifndef DATA_STRUCTURES_AND_ALGORITHMS_NATIVEEXCEPTIONS_H
#define DATA_STRUCTURES_AND_ALGORITHMS_NATIVEEXCEPTIONS_H

int BadInput(){};
int OutOfBounds(){};

#endif //DATA_STRUCTURES_AND_ALGORITHMS_NATIVEEXCEPTIONS_H
